return {
  {
    "nvimdev/lspsaga.nvim",
    event = "LspAttach",
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons",
    },
    keys = {
      { "K", "<cmd>Lspsaga hover_doc<CR>", desc = "Hover Documentation" },
      { "gd", "<cmd>Lspsaga finder<CR>", desc = "LSP Finder" },
      { "gp", "<cmd>Lspsaga peek_definition<CR>", desc = "Peek Definition" },
      { "gD", "<cmd>Lspsaga goto_definition<CR>", desc = "Go to Definition" },
      { "<leader>ca", "<cmd>Lspsaga code_action<CR>", desc = "Code Action", mode = { "n", "v" } },
      { "<leader>rn", "<cmd>Lspsaga rename<CR>", desc = "Rename" },
      { "<leader>ld", "<cmd>Lspsaga show_line_diagnostics<CR>", desc = "Line Diagnostics" },
      { "<leader>lD", "<cmd>Lspsaga show_buf_diagnostics<CR>", desc = "Buffer Diagnostics" },
      { "[d", "<cmd>Lspsaga diagnostic_jump_prev<CR>", desc = "Previous Diagnostic" },
      { "]d", "<cmd>Lspsaga diagnostic_jump_next<CR>", desc = "Next Diagnostic" },
      { "[e", function()
          require("lspsaga.diagnostic"):goto_prev({ severity = vim.diagnostic.severity.ERROR })
        end, desc = "Previous Error" },
      { "]e", function()
          require("lspsaga.diagnostic"):goto_next({ severity = vim.diagnostic.severity.ERROR })
        end, desc = "Next Error" },
      { "<leader>lo", "<cmd>Lspsaga outline<CR>", desc = "Toggle Outline" },
      { "<A-d>", "<cmd>Lspsaga term_toggle<CR>", desc = "Toggle Terminal", mode = { "n", "t" } },
    },
    opts = {
      ui = {
        border = "rounded",
        devicon = true,
        title = true,
        expand = "",
        collapse = "",
        code_action = "💡",
        actionfix = " ",
        lines = { "┗", "┣", "┃", "━", "┏" },
        kind = nil,
        imp_sign = "󰳛 ",
      },
      hover = {
        max_width = 0.6,
        max_height = 0.8,
        open_link = "gx",
        open_cmd = "!chrome",
      },
      diagnostic = {
        show_code_action = true,
        show_layout = "float",
        show_normal_height = 10,
        jump_num_shortcut = true,
        max_width = 0.8,
        max_height = 0.6,
        max_show_width = 0.9,
        max_show_height = 0.6,
        text_hl_follow = true,
        border_follow = true,
        extend_relatedInformation = false,
        diagnostic_only_current = false,
        keys = {
          exec_action = "o",
          quit = "q",
          toggle_or_jump = "<CR>",
          quit_in_show = { "q", "<ESC>" },
        },
      },
      code_action = {
        num_shortcut = true,
        show_server_name = true,
        extend_gitsigns = false,
        keys = {
          quit = "q",
          exec = "<CR>",
        },
      },
      lightbulb = {
        enable = true,
        sign = true,
        debounce = 10,
        sign_priority = 40,
        virtual_text = false,
        enable_in_insert = true,
      },
      scroll_preview = {
        scroll_down = "<C-f>",
        scroll_up = "<C-b>",
      },
      request_timeout = 2000,
      finder = {
        max_height = 0.5,
        left_width = 0.3,
        right_width = 0.3,
        methods = {},
        default = "ref+imp",
        layout = "float",
        silent = false,
        filter = {},
        fname_sub = nil,
        sp_inexist = false,
        sp_global = false,
        ly_botright = false,
        keys = {
          shuttle = "[w",
          toggle_or_open = "<CR>",
          vsplit = "s",
          split = "i",
          tabe = "t",
          tabnew = "r",
          quit = "q",
          close = "<C-c>k",
        },
      },
      definition = {
        width = 0.6,
        height = 0.5,
        keys = {
          edit = "<C-c>o",
          vsplit = "<C-c>v",
          split = "<C-c>i",
          tabe = "<C-c>t",
          tabnew = "<C-c>n",
          quit = "q",
          close = "<C-c>k",
        },
      },
      rename = {
        in_select = true,
        auto_save = false,
        project_max_width = 0.5,
        project_max_height = 0.5,
        keys = {
          quit = "<C-k>",
          exec = "<CR>",
          select = "x",
        },
      },
      symbol_in_winbar = {
        enable = false,
      },
      outline = {
        win_position = "right",
        win_width = 30,
        auto_preview = true,
        detail = true,
        auto_close = true,
        close_after_jump = false,
        layout = "normal",
        max_height = 0.5,
        left_width = 0.3,
        keys = {
          toggle_or_jump = "<CR>",
          quit = "q",
          jump = "e",
        },
      },
      callhierarchy = {
        layout = "float",
        left_width = 0.2,
        keys = {
          edit = "e",
          vsplit = "s",
          split = "i",
          tabe = "t",
          close = "<C-c>k",
          quit = "q",
          shuttle = "[w",
          toggle_or_req = "u",
        },
      },
      beacon = {
        enable = true,
        frequency = 7,
      },
      implement = {
        enable = false,
        sign = true,
        lang = {},
        virtual_text = true,
        priority = 100,
      },
    },
  },
}
