return {
  "hedyhli/outline.nvim",
  lazy = true,
  cmd = { "Outline", "OutlineOpen" },
  keys = {
    { "<leader>o", "<cmd>Outline<CR>", desc = "Toggle outline" },
  },
  opts = {
    outline_window = {
      position = "right",
      width = 30,
      relative_width = true,
      wrap = false,
      show_numbers = false,
      show_relative_numbers = false,
      show_cursorline = true,
      hide_cursor = false,
      focus_on_open = true,
      auto_close = false,
      auto_jump = false,
      jump_highlight_duration = 300,
    },
    outline_items = {
      show_symbol_details = true,
      show_symbol_lineno = false,
      highlight_hovered_item = true,
      auto_set_cursor = true,
      auto_update_events = {
        follow = { "CursorMoved" },
      },
    },
    guides = {
      enabled = true,
      markers = {
        bottom = "└",
        middle = "├",
        vertical = "│",
      },
    },
    symbol_folding = {
      autofold_depth = 1,
      auto_unfold = {
        hovered = true,
        only = true,
      },
    },
    preview_window = {
      auto_preview = false,
      open_hover_on_preview = false,
      width = 50,
      min_width = 50,
      relative_width = true,
      border = "rounded",
      winhl = "NormalFloat:",
    },
    symbols = {
      icons = {
        File = { icon = "󰈔", hl = "@text.uri" },
        Module = { icon = "󰆧", hl = "@namespace" },
        Namespace = { icon = "󰅪", hl = "@namespace" },
        Package = { icon = "󰏗", hl = "@namespace" },
        Class = { icon = "𝓒", hl = "@type" },
        Method = { icon = "ƒ", hl = "@method" },
        Property = { icon = "", hl = "@method" },
        Field = { icon = "󰆨", hl = "@field" },
        Constructor = { icon = "", hl = "@constructor" },
        Enum = { icon = "ℰ", hl = "@type" },
        Interface = { icon = "󰜰", hl = "@type" },
        Function = { icon = "", hl = "@function" },
        Variable = { icon = "", hl = "@constant" },
        Constant = { icon = "", hl = "@constant" },
        String = { icon = "𝓐", hl = "@string" },
        Number = { icon = "#", hl = "@number" },
        Boolean = { icon = "⊨", hl = "@boolean" },
        Array = { icon = "󰅪", hl = "@constant" },
        Object = { icon = "⦿", hl = "@type" },
        Key = { icon = "🔐", hl = "@type" },
        Null = { icon = "NULL", hl = "@type" },
        EnumMember = { icon = "", hl = "@field" },
        Struct = { icon = "𝓢", hl = "@type" },
        Event = { icon = "🗲", hl = "@type" },
        Operator = { icon = "+", hl = "@operator" },
        TypeParameter = { icon = "𝙏", hl = "@parameter" },
        Component = { icon = "󰅴", hl = "@function" },
        Fragment = { icon = "󰅴", hl = "@constant" },
        TypeAlias = { icon = " ", hl = "@type" },
        Parameter = { icon = " ", hl = "@parameter" },
        StaticMethod = { icon = " ", hl = "@function" },
        Macro = { icon = " ", hl = "@macro" },
      },
    },
  },
}
